name: Frontend

on:
  push:
    branches: [main]
  pull_request:
env:
  PORT: ${{ vars.PORT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.x
          cache: "pnpm"

      - name: Install all dependencies
        run: |
          pnpm install --frozen-lockfile --prefer-offline

      - name: Build the frontend
        working-directory: apps/frontend
        run: |
          pnpm run build
